pacilflix/langganan/urls.py
from django.urls import path
from .views import manage_subscription, buy_package, purchase_package_view

app_name = 'langganan'

urlpatterns = [
    path('', manage_subscription, name='manage_subscription'),
    path('buy/', buy_package, name='buy_package'),
    path('purchase/', purchase_package_view, name='purchase_package'),
]

pacilflix/main/urls.py
from django.urls import path
from main.views import show_main, show_trailer, show_tayangan, kirim_ulasan, show_episode, show_detail_tayangan
from main.views import show_main

app_name = 'main'

urlpatterns = [
    path('home/', show_main, name='show_main'),
    path('trailer/', show_trailer, name='trailer'),
    path('tayangan/', show_tayangan, name='tayangan'),
    path('tayangan/<str:id_tayangan>',
         show_detail_tayangan, name='tayangan-detail'),
    path('tayangan/<str:id_tayangan>/episode/<str:sub_judul>/',
         show_episode, name='episode'),
    path('ulasan/<str:id_tayangan>', kirim_ulasan, name='ulasan'),
]

pacilflix/pacilflix/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
    path('daftar_unduhan/', include('daftar_unduhan.urls')),
    path('daftar_favorit/', include('daftar_favorit.urls')),
    path('', include('main.urls')),
    path('', include('authentication.urls')),
    path('contributors/', include('konstributor.urls')),
    path('manage/', include('langganan.urls')),
    path('buy/', include('langganan.urls')),
    path('purchase/', include('langganan.urls')),
]

pacilflix/langganan/models.py
from django.db import models

pacilflix/langganan/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse
from .services import get_active_subscription, get_available_packages, get_transaction_history, purchase_package
from utils.get_user import get_user

def manage_subscription(request: HttpRequest) -> HttpResponse:
    user = request.user.username
    active_subscription = get_active_subscription(user)
    available_packages = get_available_packages()
    transaction_history = get_transaction_history(user)

    context = {
        "active_subscription": active_subscription,
        "available_packages": available_packages,
        "transaction_history": transaction_history,
        "islogin": get_user(request=request) != None
    }

    return render(request, 'langganan.html', context)

def buy_package(request: HttpRequest) -> HttpResponse:
    package_name = request.GET.get('package')
    if package_name:
        packages = get_available_packages()
        package = next((p for p in packages if p['nama'] == package_name), None)
        if package:
            context = {
                "nama": package["nama"],
                "harga": package["harga"],
                "resolusi_layar": package["resolusi_layar"],
                "dukungan_perangkat": package["dukungan_perangkat"],
                "islogin": get_user(request=request) != None
            }
            return render(request, 'beli_paket.html', context)
    return redirect('langganan:manage_subscription')

def purchase_package_view(request: HttpRequest) -> HttpResponse:
    if request.method == 'POST':
        user = request.user.username
        package_name = request.POST.get('nama')
        payment_method = request.POST.get('metode_pembayaran')
        if user and package_name and payment_method:
            purchase_package(user, package_name, payment_method)
            return redirect('langganan:manage_subscription')
    return redirect('langganan:manage_subscription')

pacilflix/langganan/templates/beli_paket.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">

    <title>Subscribe</title>

    <style>
        .navbar {
            background-color: #333;
            padding: 12px 0;
            overflow: hidden;
            display: flex;
            justify-content: space-between;
        }
        .navbar a {
            color: white;
            padding: 10px 20px;
            text-decoration: none;
            font-size: 20px;
        }
        .navbar a:hover {
            background-color: #555;
        }
        .search-container {
            display: flex;
            align-items: center;
        }
        .search-container input[type="text"], .search-container button {
            padding: 8px;
            margin: 4px 2px;
            border: none;
            border-radius: 4px;
        }
        .search-container input[type="text"] {
            flex-grow: 1;
        }
        .search-container button {
            background-color: #555;
            color: white;
            cursor: pointer;
        }
        .search-container button:hover {
            background-color: #666;
        }
        .card-container {
            display: flex;
            overflow-x: auto;
            gap: 20px;
            padding: 20px;
        }
        body, h1, th {
            margin: 0;
            padding: 0;
            font-family: 'Montserrat', sans-serif;
            background-color: #06041f;
            color: #fff;
        }
        .container {
            width: 80%;
            margin: 20px auto;
            text-align: center;
        }
        h1 {
            color: #fff;
            margin-bottom: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            background-color: #fff;
            color: #333;
            margin-bottom: 20px;
        }
        th {
            background-color: #380d0d;
            color: white;
            text-align: center;
        }
        td {
            padding: 8px;
            text-align: left;
            vertical-align: middle;
        }
        tr {
            border-bottom: 10px solid #06041f;
        }
        .centered {
            text-align: center;
        }
        
        .dropbtn {
        background-color: #e50914;
        color: white;
        padding: 16px;
        font-size: 16px;
        border: none;
        cursor: pointer;
        }

        .dropbtn:hover, .dropbtn:focus {
        background-color: #f63535;
        }

        .dropdown {
        position: relative;
        display: inline-block;
        }

        .dropdown-content {
        display: none;
        position: absolute;
        background-color: #f6f6f6;
        min-width: 230px;
        border: 1px solid #ddd;
        z-index: 1;
        }

        .dropdown-content a {
        color: black;
        padding: 12px 16px;
        text-decoration: none;
        display: block;
        }

        .dropdown-content a:hover {background-color: #f1f1f1}

        .show {display:block;}
    </style>
    

    <div class="container">
        <h1>HALAMAN BELI</h1>
        <h3>Informasi Paket yang Ingin Dibeli</h3>
        <table border="1">
            <tr>
                <th>Nama</th>
                <th>Harga</th>
                <th>Resolusi Layar</th>
                <th>Dukungan Perangkat</th>
            </tr>
            <tr>
                <td>{{ nama }}</td>
                <td>{{ harga }}</td>
                <td>{{ resolusi_layar }}</td>
                <td>{{ dukungan_perangkat|join:", " }}</td>
            </tr>
        </table>

        </table>
        <h2>Pilih Metode Pembayaran:</h2>
        <form method="post" action="{% url 'langganan:purchase_package' %}">
            {% csrf_token %}
            <input type="hidden" name="package_name" value="{{ package_details.name }}">
            <label for="payment_method">Metode Pembayaran:</label>
            <select id="payment_method" name="payment_method">
                <option value="transfer">Transfer</option>
                <option value="credit_card">Kartu Kredit</option>
                <option value="ewallet">E-Wallet</option>
            </select>
            <button type="submit">Bayar</button>
        </form>
        <!-- <h3>Pilih Metode Pembayaran</h3>
        <div class="dropdown">
            <button onclick="myFunction()" class="dropbtn">Pilih Opsi</button>
            <div id="myDropdown" class="dropdown-content">
              <a href=#>Transfer Bank</a>
              <a href=#>Kartu Kredit</a>
              <a href=#>E-Wallet</a>
            </div>
        </div> -->
    </div>
</head>
<script>
    $(document).ready(function() {
        $('#purchaseForm').submit(function(event) {
            event.preventDefault(); // Prevent the default form submission

            $.post($(this).attr('action'), $(this).serialize(), function(response) {
                alert("Terimakasih telah membeli paket ini");
                window.location.href = "{% url 'langganan:manage_subscription' %}";
            });
        });
    });
</script>

pacilflix/langganan/templates/langganan.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">

    <title>Subscribe</title>

    <style>
        .navbar {
            background-color: #333;
            padding: 12px 0;
            overflow: hidden;
            display: flex;
            justify-content: space-between;
        }

        .navbar a {
            color: white;
            padding: 10px 20px;
            text-decoration: none;
            font-size: 20px;
        }

        .navbar a:hover {
            background-color: #555;
        }

        .search-container {
            display: flex;
            align-items: center;
        }

        .search-container input[type="text"],
        .search-container button {
            padding: 8px;
            margin: 4px 2px;
            border: none;
            border-radius: 4px;
        }

        .search-container input[type="text"] {
            flex-grow: 1;
        }

        .search-container button {
            background-color: #555;
            color: white;
            cursor: pointer;
        }

        .search-container button:hover {
            background-color: #666;
        }

        .card-container {
            display: flex;
            overflow-x: auto;
            gap: 20px;
            padding: 20px;
        }

        body,
        h1,
        th {
            margin: 0;
            padding: 0;
            font-family: 'Montserrat', sans-serif;
            background-color: #06041f;
            color: #fff;
        }

        .container {
            width: 80%;
            margin: 20px auto;
            text-align: center;
        }

        h1 {
            color: #fff;
            margin-bottom: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            background-color: #fff;
            color: #333;
            margin-bottom: 20px;
        }

        th {
            background-color: #380d0d;
            color: white;
            text-align: center;
        }

        td {
            padding: 8px;
            text-align: left;
            vertical-align: middle;
        }

        tr {
            border-bottom: 10px solid #06041f;
        }

        .centered {
            text-align: center;
        }

        .beli-btn {
            padding: 6px 12px;
            background-color: #e50914;
            border: none;
            border-radius: 4px;
            color: white;
            text-decoration: none;
            cursor: pointer;
            font-size: 14px;
            transition: background-color 0.2s;
            display: inline-block;
        }

        .beli-btn:hover {
            background-color: #f63535;
        }
    </style>

    {% include 'navbar.html' with islogin=islogin %}
    <div class="container">
        <h1>HALAMAN KELOLA LANGGANAN</h1>
        <h2>Paket Langganan Aktif Anda:</h2>
        <table border="1">
            <tr>
                <th>Nama</th>
                <th>Harga</th>
                <th>Resolusi Layar</th>
                <th>Dukungan Perangkat</th>
                <th>Tanggal Dimulai</th>
                <th>Tanggal Akhir</th>
            </tr>
            {% if active_subscription %}
            <tr>
                    <td>{{ active_subscription.nama }}</td>
                    <td>{{ active_subscription.harga }}</td>
                    <td>{{ active_subscription.resolusi_layar }}</td>
                    <td>{{ active_subscription.dukungan_perangkat|join:", " }}</td>
                    <td>{{ active_subscription.start_date_time }}</td>
                    <td>{{ active_subscription.end_date_time }}</td>
            </tr>
            {% else %}
            <tr>
                    <td colspan="6">Tidak ada paket aktif</td>
            </tr>
            {% endif %}
        </table>


        <h2>Pilih Paket Lain:</h2>
        <table border="1">
            <tr>
                <th>Nama</th>
                <th>Harga</th>
                <th>Resolusi Layar</th>
                <th>Dukungan Perangkat</th>
                <th>Beli</th>
            </tr>
            {% for package in available_packages %}
            <tr>
                <td>{{ package.nama }}</td>
                <td>{{ package.harga }}</td>
                <td>{{ package.resolusi_layar }}</td>
                <td>{{ package.dukungan_perangkat|join:", " }}</td>
                <td><button><a href="{% url 'langganan:buy_package' %}?package={{ package.nama }}">Beli</a></button></td>
            </tr>
            {% endfor %}
        </table>

        <h2>Riwayat Transaksi:</h2>
        <table border="1">
            <thead>
                <tr>
                    <th>Nama Paket</th>
                    <th>Tanggal Dimulai</th>
                    <th>Tanggal Akhir</th>
                    <th>Metode Pembayaran</th>
                    <th>Tanggal Pembayaran</th>
                    <th>Total Pembayaran</th>
                </tr>
            </thead>
            <tbody>
                {% for transaction in transaction_history %}
                <tr>
                    <td>{{ transaction.nama_paket }}</td>
                    <td>{{ transaction.start_date_time }}</td>
                    <td>{{ transaction.end_date_time }}</td>
                    <td>{{ transaction.metode_pembayaran }}</td>
                    <td>{{ transaction.timestamp_pembayaran }}</td>
                    <td>{{ transaction.harga }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</head>